---
title: "R Setup"
---
1. Get you R ready! Start with installing all required packages (Don't forget to cite microViz package in publications):

```{r setup, include=FALSE}
mylib = 'C:\\Users\\zuendj\\Documents\\R4Libs' #replace with the directory of library
.libPaths(mylib)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(echo = TRUE, warning = FALSE, message = FALSE)

##tidyverse
install.packages("tidyverse")
library(tidyverse)

##phyloseq
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("phyloseq")
library(phyloseq)

##microviz
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install(c("phyloseq", "microbiome", "ComplexHeatmap"), update = FALSE)
install.packages(
  "microViz",
  repos = c(davidbarnett = "https://david-barnett.r-universe.dev", getOption("repos"))
)
library(microViz)

##other packages
install.packages(rlang)
library(rlang)
install.packages(openxlsx)
library(openxlsx)
install.packages(rstatix)
library(rstatix)
install.packages(ggpubr)
library(ggpubr)
install.packages(plyr)
library(plyr)
install.packages(ggpmisc)
library(ggpmisc)
```

2. Load additional R functions from zenodo fconstancias: https://zenodo.org/records/6473394 (Note: don't forget to cite) - only if needed
```{r}
#download the functions and store them locally on your computer=> from fconstancias: https://zenodo.org/records/6473394 
#load them into R => replace directory with the directory on your computer
# source("C:/Users/zuendj/Desktop/03_data R/divcom_functions/R/phyloseq_taxa_tests.R") 
# source("C:/Users/zuendj/Desktop/03_data R/divcom_functions/R/phyloseq_normalisation.R") 
# source("C:/Users/zuendj/Desktop/03_data R/divcom_functions/R/phyloseq_alpha.R") 
# source("C:/Users/zuendj/Desktop/03_data R/divcom_functions/R/phyloseq_beta.R") 
# source("C:/Users/zuendj/Desktop/03_data R/divcom_functions/R/phyloseq_heatmap.R")
# source("C:/Users/zuendj/Desktop/03_data R/divcom_functions/R/phyloseq_taxa_tests.R")


#function for getting metadata file
sample.data.frame <- function(ps) {
  return(as(phyloseq::sample_data(ps), "data.frame"))}
```